# Generated by Django 3.0.14 on 2021-09-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_userquestionjunction_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionjunction',
            name='is_report',
            field=models.CharField(db_index=True, default='', max_length=250),
        ),
    ]
